# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='home/')),
                ('image_caption', models.TextField(max_length=144)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Category')),
            ],
        ),
    ]
