# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=144),
        ),
    ]
