# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_auto_20190319_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
    ]
