# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0008_auto_20190319_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
